name: Update Package Artifacts
on:
  push:
    branches: '*'
#     branches: [main]
#   pull_request:
#     branches: [main]
jobs:
  Update-NPM-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest branch
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
      - name: Bump package.json version
        run: ./gitops/github-event-check.sh
      - name: do composite action
      - uses: ./.github/workflows/example.yml
