name: Reusable workflow example
on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
jobs:
  example_job:
    name: sample re-use
    runs-on: ubuntu-latest
    steps:
      - name: 'thing'
        run: echo "hello"
