name: Validate Schema Changes
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
jobs:
  Validate-Schema-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Schema Registries
        uses: actions/checkout@v2
      - run: echo "Validating the schema registry"
      - run: docker run -v  "$(pwd)":/data domnikl/schema-registry-gitops plan --properties /data/gitops/configuration.properties /data/gitops/schema-registry.yml
